/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link';
import {server} from '../Config/index'
import {userAuth} from "../Contexts/AllContext"
import { useRouter } from 'next/router'
import Image from 'next/image'
import Carousel from 'react-bootstrap/Carousel';
import 'animate.css'

interface homeprops {
  data: {
    _id: string,
    surname: string,
    lastname: string,
    nickname: string,
    image: string,
    phone: string,
    matric: string,
    bio: string,
    password: string
  }[]
}

interface profiler {
    _id: string | null,
    surname: string | null,
    lastname: string | null,
    nickname: string | null,
    matric: string | null,
    bio: string | null,
  
}

const Home = ({data}:homeprops) => {
  const {loggedIn,profile} = userAuth()
  const {_id , surname} = profile
  const router = useRouter()

  const onClickComrade = (comradeId:string) => {
    if(loggedIn && _id === comradeId) {
      router.push('/dashboard')
    }
    else{
      router.push(`/comrade/${comradeId}`)
    }
  }
  
  return (
    <div>
      <Head>
        <title>Yabatech College of Techn ology, Mechanical Engineering set of 2022 part time website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
       <main className='main'>
      <nav className='navs'>
            <div className='flexIt'>
            <div className='logoName'>
              MECH22
            </div>
            <div className='space'></div>
            <div>
              { surname ? <Link href='/dashboard'>
                 <div className='loginName'>
              <Image
                src="https://img.icons8.com/material-rounded/24/000000/person-male.png"
                alt="person"
                width={20}
                height={20}
                  />
                <div>{surname}</div>
                </div>
                </Link> :
              <Link href='/Login' style={{cursor: 'pointer'}}>
              <div className='Login'>Login</div>
              </Link>
}
            </div>
            </div>
          </nav>
        <div className='banner'>

          <div className='BannerHeading'>
            <div className='animate__animated animate__backInDown'>
            <div className='bigHeader'>MECHANICAL ENGINEERING</div>
            <div className='bigHeader'>CLASS OF 2022(PT)</div>
           <div className='smallHeader'>NA WHO GIVE UP,</div>
           <div className='smallHeader'>FUCK UP! </div>  
          
          <Link href='/pictures/1'>
           <button className='gallery'>
            <span>Gallery</span>
            <div className='galleryImageDiv'>
            <Image
            src="https://img.icons8.com/external-royyan-wijaya-detailed-outline-royyan-wijaya/24/ffffff/external-arrow-arrow-line-royyan-wijaya-detailed-outline-royyan-wijaya-13.png"
            alt="arrow"
            width={20}
            height={20}
            />
            </div>
           </button>
           </Link>
           </div>
          </div> 
          <div>
            <div className='gridBannerImg'>
            <img 
            src='https://res.cloudinary.com/chiaka/image/upload/v1666196649/mr.patrick_hnccqs.jpg'
            alt='banner image'
            className='gridImg animate__animated animate__backInUp animate__delay-4s'
            />
            <img 
            src='https://res.cloudinary.com/chiaka/image/upload/v1666196664/savior_dance_p6jxhf.jpg'
            alt='banner image'
            className='gridImg animate__animated animate__backInUp animate__delay-3s'
            />
            <img 
            src='https://res.cloudinary.com/chiaka/image/upload/v1661193316/xn37e773ch3ifmkifzvl.jpg'
            alt='banner image'
            className='gridImg animate__animated animate__backInUp animate__delay-2s'
            />
            </div>
      <div className='gridBannerImg2'>
      <div className='gridImg animate__animated animate__backInUp animate__delay-1s'>
      <Carousel fade>
      <Carousel.Item>
        <img
          className="gridImg"
          src="https://res.cloudinary.com/chiaka/image/upload/v1666196490/ekene_jubril_rxwevm.jpg"
          alt="First slide"
        />
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="gridImg"
          src="https://res.cloudinary.com/chiaka/image/upload/v1666196531/3wiseladies_ain43j.jpg"
          alt="Second slide"
        />
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="gridImg"
          src="https://res.cloudinary.com/chiaka/image/upload/v1661193783/me3nlmqwy9izyeuq9h5l.jpg"
          alt="Third slide"
        />
      </Carousel.Item>
    </Carousel>
    </div>
    <div className='animate__animated animate__backInUp'>
    <Carousel fade>
      <Carousel.Item>
        <img
          className="bannerImg"
          src="https://res.cloudinary.com/chiaka/image/upload/v1665289795/DSC_6649_ox6uz4.jpg"
          alt="First slide"
        />
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="bannerImg"
          src="https://res.cloudinary.com/chiaka1996/image/upload/v1658609043/mechanical_eng_banner2_d0m51n.jpg"
          alt="Third slide"
        />
      </Carousel.Item>
    </Carousel>
    </div>
    </div>
          </div>
        </div> 

        <section className='studentSection'>
          <div className='studentHeader' >COMRADES</div>
          <div className='comradeGrid'>
         
          {
            data.map((element,i) => <div onClick={() => onClickComrade(element._id)} key={i}>
              <div className='imageHolder'>
              <img 
              src={element.image.length > 1 ? element.image : 'https://res.cloudinary.com/chiaka/image/upload/v1664259165/person-icon-person-icon-17_o9gnwh.jpg'}
              alt='description of comrade'
              className='comradePics'
              />
              <div className='comradeName'>{element.surname + ' ' + element.lastname}</div>
              <div className='comradeAKA'>{element.nickname}</div>
            </div>
          </div>
             )
          }
          </div>

        </section>

       
      </main>

      <footer className='footer'>
        YABA COLLEGE OF TECHNOLOGY, MECHANICAL ENGINEERING(PT) CLASS OF 2022
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  try{
    let response = await fetch(`${server}/api/getProfile`)
    const data = await response.json()
    
    return{
      props: {data}
    }
    
  }
  catch(error:any){
    alert(error.message)
  }
}

export default Home
